---
- name: Docker Compose
  hosts: all
  remote_user: jenkins
  become: true
  vars:
    ansible_ssh_private_key_file: /home/shubham/.ssh/id_rsa

  tasks:
    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Pull Dataset Image
      docker_image:
        name: "zanzadshubham25/dataset"
        source: pull
      register: docker_pull_dataset

    - name: Display Docker Pull Result for Dataset Image
      debug:
        var: docker_pull_dataset

    - name: Pull Frontend Image
      docker_image:
        name: "zanzadshubham25/frontend"
        source: pull
      register: docker_pull_frontend

    - name: Display Docker Pull Result for Frontend Image
      debug:
        var: docker_pull_frontend
      
    - name: Pull Backend Image
      docker_image:
        name: "zanzadshubham25/backend"
        source: pull
      register: docker_pull_backend

    - name: Display Docker Pull Result for Backend Image
      debug:
        var: docker_pull_backend

    -name: Copy Docker Compose file to host
     copy: 
      src: /var/lib/jenkins/workspace/LeagueFit/docker-compose.yml
      dest: /opt/docker-compose.yml

    - name: Start Docker Compose services
      command: docker-compose up -d
      args:
        chdir: /opt/
