---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: jenkins
  become: true
  vars:
    ansible_ssh_private_key_file: /home/shubham/.ssh/id_rsa

  tasks:
    - name: Pull Dataset Image
      docker_image:
        name: "zanzadshubham25/dataset"
        source: pull
      register: docker_pull_dataset

    - name: Display Docker Pull Result for Dataset Image
      debug:
        var: docker_pull_dataset

    - name: Pull Frontend Image
      docker_image:
        name: "zanzadshubham25/frontend"
        source: pull
      register: docker_pull_frontend

    - name: Display Docker Pull Result for Frontend Image
      debug:
        var: docker_pull_frontend

    - name: Pull Backend Image
      docker_image:
        name: "zanzadshubham25/backend"
        source: pull
      register: docker_pull_backend

    - name: Display Docker Pull Result for Backend Image
      debug:
        var: docker_pull_backend

    - name: Copy docker-compose to /opt/
      copy:
        src: /var/lib/jenkins/workspace/LeagueFit/docker-compose.yml
        dest: /opt/docker-compose.yml

    - name: Copy requirements.txt to /opt/
      copy:
        src: /var/lib/jenkins/workspace/LeagueFit/backend/requirements.txt
        dest: /opt/requirements.txt

    - name: Start Docker Compose services
      command: docker-compose up -d
      args:
        chdir: /opt/
