- name: Deploy LeagueFit
  hosts: localhost
  remote_user: jenkins
  become: true
  vars:
    ansible_ssh_private_key_file: /home/shubham/.ssh/id_rsa

  tasks:
    - name: Pull Dataset Image
      docker_image:
        name: "zanzadshubham25/dataset"
        source: pull
      register: docker_pull_dataset

    - name: Display Docker Pull Result for Dataset Image
      debug:
        var: docker_pull_dataset

    - name: Pull Frontend Image
      docker_image:
        name: "zanzadshubham25/frontend"
        source: pull
      register: docker_pull_frontend

    - name: Display Docker Pull Result for Frontend Image
      debug:
        var: docker_pull_frontend

    - name: Pull Backend Image
      docker_image:
        name: "zanzadshubham25/backend"
        source: pull
      register: docker_pull_backend

    - name: Display Docker Pull Result for Backend Image
      debug:
        var: docker_pull_backend

    - name: Start Docker Compose services
      command: whoami
      register: current_working_directory

    - name: Display current working directory
      debug:
        var: current_working_directory.stdout

    - name: Copy project directory to target
      copy:
        src: /var/lib/jenkins/workspace/LeagueFit/
        dest: /opt/LeagueFit/

    - name: Build Docker Compose services
      command: docker-compose up --build -d
      args:
        chdir: /opt/LeagueFit/
