---
- name: Deploy LeagueFit
  hosts: localhost
  remote_user: jenkins
  become: true
  vars:
    ansible_ssh_private_key_file: /home/shubham/.ssh/id_rsa

  tasks:It seems like you're encountering a permission denied error while trying to stop a container named dataset. This error is likely occurring because the user running the Docker commands does not have the necessary permissions to stop the container.

Here are a few steps you can take to troubleshoot and potentially resolve this issue:

    Check Docker Permissions: Ensure that the user running the Docker commands has the necessary permissions to manage containers. Typically, this user needs to be a member of the docker group.

    Verify Container Ownership: Check the ownership of the Docker containers and related files. Ensure that the user running the Docker commands has appropriate ownership or permissions to manage these resources.
    - name: Pull Dataset Image
      docker_image:
        name: "zanzadshubham25/dataset"
        source: pull
      register: docker_pull_dataset

    - name: Display Docker Pull Result for Dataset Image
      debug:
        var: docker_pull_dataset

    - name: Pull Frontend Image
      docker_image:
        name: "zanzadshubham25/frontend"
        source: pull
      register: docker_pull_frontend

    - name: Display Docker Pull Result for Frontend Image
      debug:
        var: docker_pull_frontend

    - name: Pull Backend Image
      docker_image:
        name: "zanzadshubham25/backend"
        source: pull
      register: docker_pull_backend

    - name: Display Docker Pull Result for Backend Image
      debug:
        var: docker_pull_backend

    - name: Start Docker Compose services
      command: whoami
      register: current_working_directory

    - name: Display current working directory
      debug:
        var: current_working_directory.stdout


    # - name: Copy project directory to target
    #   copy:
    #     src: /var/lib/jenkins/workspace/LeagueFit/
    #     dest: /opt/LeagueFit/

    - name: Build Docker Compose services
      command: docker-compose up --build -d 
      # args:
      #   chdir: /opt/

    # - name: Start Docker Compose services in detached mode
    #   command: docker-compose up -d
    #   # args:
    #   #   chdir: /opt/
