- name: Deploy LeagueFit
  hosts: localhost
  remote_user: shubham
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_ssh_private_key_file: /home/shubham/.ssh/id_rsa

  tasks:
    - name: Pull Dataset Image
      community.general.docker_image:
        name: "zanzadshubham25/dataset"
        source: pull
        force_source: true
      register: docker_pull_dataset

    - name: Display Docker Pull Result for Dataset Image
      debug:
        var: docker_pull_dataset

    - name: Pull Backend Image
      community.general.docker_image:
        name: "zanzadshubham25/backend"
        source: pull
        force_source: true
      register: docker_pull_backend

    - name: Display Docker Pull Result for Backend Image
      debug:
        var: docker_pull_backend
      
    - name: Pull Frontend Image
      community.general.docker_image:
        name: "zanzadshubham25/frontend"
        source: pull
        force_source: true
      register: docker_pull_frontend

    - name: Display Docker Pull Result for Frontend Image
      debug:
        var: docker_pull_frontend

    - name: Start Docker Compose
      service:
        name: docker
        state: started
    - name: Run Docker Compose
      shell: docker-compose up -d
      args:
        chdir: /home/shubham/Desktop/SPE_FINAL/LeagueFit