- name: Pull Docker Images and Run Docker Compose
  hosts: localhost
  become: false  # Avoid `become` as unnecessary and potentially insecure

  tasks:
    - name: Pull Docker Images
      docker_image:
        name: "{{ item }}"
        state: present  # Use 'present' for consistency (pulls if missing)
      loop:
        - zanzadshubham25/dataset
        - zanzadshubham25/backend
        - zanzadshubham25/frontend
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Verify Docker service is running 
      service:
        name: docker
        state: started
      register: docker_service_result

    - name: Stop Docker Compose services
        name: docker-compose down
        become: true
        shell: docker-compose down

    - name: Start Docker Compose services
      name: Run docker-compose up -d
      become: true  
      shell: docker-compose up -d