---
- name: Pull Docker Images in Order
  hosts: localhost
  remote_user: jenkins
  become: true
  vars:
    ansible_ssh_private_key_file: /home/shubham/.ssh/id_rsa
    images:
      - name: "zanzadshubham25/dataset"
      - name: "zanzadshubham25/frontend"
      - name: "zanzadshubham25/backend"

  tasks:
  - loop: "{{ images }}"
    loop_control:
      loop_var: image
    tasks:
      - name: Pull Image {{ image.name }}
        docker_image:
          name: "{{ image.name }}"
          source: pull
        register: docker_pull_result

      - name: Display Docker Pull Result for Image {{ image.name }}
        debug:
          var: docker_pull_result

      - debug:
          msg: "Waiting for previous image pull to finish"
        when: image.name != images[0].name  # Skip waiting for the first image

  - name: Start Docker Compose services
    docker_compose:
      project_src: /home/shubham/Desktop/SPE_Final/LeagueFit/docker-compose.yml
      state: started
