---
- name: Pull Docker Images and Run Docker Compose
  hosts: localhost
  remote_user: shubham
  become: false
  tasks:
    - name: Pull Docker Images
      docker_image:
        name: "{{ item }}"
        source: pull
      loop:
        - zanzadshubham25/dataset
        - zanzadshubham25/backend
        - zanzadshubham25/frontend
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Copy Docker Compose file to host
      copy: 
        src: /var/lib/jenkins/workspace/LeagueFit/docker-compose.yml
        dest: /opt/docker-compose.yml
    
    - name: Start Docker Compose
      command: docker-compose up -d
      args:
        chdir: /opt/
