version: '3.8'

services:
  dataset:
    build: 
      context: ./dataset
    container_name: dataset
    volumes:
      - dataset:/app
    ports:
      - "80:80"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://dataset:80/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:  
      - ./backend:/app
      - dataset:/dataset
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://dataset:80/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: 
      context: ./frontend
    container_name: frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
      - dataset:/dataset
    networks:
      - app-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://backend:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  dataset:
