version: "3.8"
services:
  dataset:
    build:
      context: ./dataset
    container_name: dataset
    ports:
      - "8008:8008"
    volumes:
      - ./dataset:/app
    networks:
      - app-network
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - app-network
    depends_on:
      - dataset
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  dataset:
